// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwcfr7P8SQ59ZzvvHc64aS7bIUdqEmIns',
    appId: '1:990997124976:web:05abb71fb0bc128c07e1b5',
    messagingSenderId: '990997124976',
    projectId: 'fir-notification-77c65',
    authDomain: 'fir-notification-77c65.firebaseapp.com',
    storageBucket: 'fir-notification-77c65.appspot.com',
    measurementId: 'G-5DMMWLM400',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmxVOZK2Bg-3OTn0MRcVO_UlPnY4rfptc',
    appId: '1:990997124976:android:49f2a7264922c47507e1b5',
    messagingSenderId: '990997124976',
    projectId: 'fir-notification-77c65',
    storageBucket: 'fir-notification-77c65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4Smov19fCb3rD92d-qEjlBCA1HbejDw',
    appId: '1:990997124976:ios:bf7b17f2fcd1548407e1b5',
    messagingSenderId: '990997124976',
    projectId: 'fir-notification-77c65',
    storageBucket: 'fir-notification-77c65.appspot.com',
    iosBundleId: 'com.example.quizDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4Smov19fCb3rD92d-qEjlBCA1HbejDw',
    appId: '1:990997124976:ios:bf7b17f2fcd1548407e1b5',
    messagingSenderId: '990997124976',
    projectId: 'fir-notification-77c65',
    storageBucket: 'fir-notification-77c65.appspot.com',
    iosBundleId: 'com.example.quizDemo',
  );
}
